### ISSUE TITLE
Great extension but doesn't work on tumblr pages!

### ISSUE THREAD

**Issue by goldenbeautys** [eramdam/GifsOnTumblr#1]
I love this extension, and it works on apps pretty well. However it doesn't work on tumblr pages themselves. Which is at no fault of the creator, as it just recently changed the coding to .webp on a tumblr page recently. I just thought I'd point it out, etc! Love the idea of this cause tumblr's new coding/google's coding sucks.

**Comment by eramdam** [comment]
I've been told about this yeah. I'm still not sure how to tackle this because not all tumblr blogs necessary have an URL with `.tumblr.com` in it so it's a bit tricky. I might have to find a workaround somehow.

**Comment by eramdam** [comment]
Forgot to close this but it's supported now.
