### ISSUE TITLE
Gifs not moving

### ISSUE THREAD

**Issue by nyna237** [eramdam/GifsOnTumblr#2]
Tumblr just changed the gif limit to 8MB and it appears that if this extension is active that gifs that at the new limit (or perhaps just over the old 3MB one?) are not moving on my dashboard. I'm using Chrome on both a Windows 10 Pro desktop and a Chromebook. I'm seeing the issue with both platforms.

**Comment by eramdam** [comment]
@nyna237 could you link to posts were this happens?

**Comment by nyna237** [comment]
https://rose-tylers.tumblr.com/post/188778383554/the-most-beautiful-girl-in-the-universe

This is my friend's post. When viewed on my dash with the extension enabled, it doesn't move. If I click on the image to open it or view it on her blog or the reblog on mine, it is moving just fine. I've noticed it with other posts, where one or two gifs won't be moving but the rest will. As soon as I disable the extension and refresh the page, it's fine. As I see other examples I'll add them to this.

**Comment by eramdam** [comment]
@nyna237 hum, yeah I'm not sure how I can easily display that specific post in the dashboard? 😅

**Comment by eramdam** [comment]
Closing because I'm not sure I can do much
