### ISSUE TITLE
The extension doesn’t work with Tumblr’s new dashboard update

### ISSUE THREAD

**Issue by saravg** [eramdam/GifsOnTumblr#4]
Hi! This extension has worked amazingly for the past months, but sadly, with Tumblr’s new dashboard update, it’s stopped working. I think the issue can be fixed pretty quickly though, but since it’s your code, I think it’s better to give you the suggestion, if you allow me, here.

This new update adds a new attribute to `img` tags, called `srcset`. I tested, and adding that attribute to the ones already on the code fix the issue.

Thank you so much in advance.

**Comment by eramdam** [comment]
Just submitted 1.1.1 on Chrome/Firefox extensions store that implements the fix https://github.com/eramdam/GifsOnTumblr/commit/4f34bbb0f0be1621c0fd839eb0c43ab18f8ab25d.
